spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true #开启能识别表单提交的put和delete请求
    contentnegotiation:
      favor-parameter: true #开启参数类型的内容协商 format=json
#    static-path-pattern: /static/** #配置静态资源路径访问前缀
#  resources:
#    static-locations: classpath:/static/ #配置静态资源路径
#    add-mappings: false #禁用掉静态资源
